
    create table empresa (
       id bigint generated by default as identity,
        cnpj varchar(255),
        email varchar(255),
        empresa varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table empresa (
       id bigint generated by default as identity,
        cnpj varchar(255),
        email varchar(255),
        empresa varchar(255),
        nome varchar(255),
        primary key (id)
    );
